from .completed_orders import CompletedOrders
from .incomplete_orders import IncompleteOrders
from .expensive_products import ExpensiveProducts
from .inexpensive_products import InexpensiveProducts
from .favorite_sellers_by_customer import FavoriteSellersByCustomer